function marker_label_default = get_marker_label_default()
marker_label_trunk = {'Top.Head','Sternum','R.Acromium','L.Acromium'};
marker_label_pelvis = {'V.Sacral','R.ASIS','L.ASIS'};
marker_label_thigh = {'R.Knee.Lat','R.Knee.Med','L.Knee.Lat','L.Knee.Med'};
marker_label_thigh_track = {'R.Thigh1','R.Thigh2','R.Thigh3','R.Thigh4','R.Thigh.Front',...
    'L.Thigh1','L.Thigh2','L.Thigh3','L.Thigh4','L.Thigh.Front'};
marker_label_shank = {'R.Ankle.Lat','R.Ankle.Med','L.Ankle.Lat','L.Ankle.Med'};
marker_label_shank_track = {'R.Shank1','R.Shank2','R.Shank3','R.Shank4','R.Shank.Front',...
    'L.Shank1','L.Shank2','L.Shank3','L.Shank4','L.Shank.Front'};
marker_label_foot = {'R.Toe.Tip','R.Toe.Lat','R.Toe.Med','R.Heel.Lat','R.Heel.Med','R.Heel',...
    'L.Toe.Tip','L.Toe.Lat','L.Toe.Med','L.Heel.Lat','L.Heel.Med','L.Heel'};
marker_label_default = [marker_label_trunk,marker_label_pelvis,marker_label_thigh,...
    marker_label_thigh_track,marker_label_shank,marker_label_shank_track,...
    marker_label_foot];
end