function marker_header = get_marker_header(header_information)
line_1 = {'PathFileType',num2str(header_information.number_type_file),'(X/Y/Z)',...
    header_information.path_file};
line_2 = {'DataRate','CameraRate','NumFrames','NumMarkers','Units',...
    'OrigDataRate','OrigDataStartFrame','OrigNumFrames'};
line_3 = {num2str(header_information.rate_data),num2str(header_information.rate_camera),...
    num2str(header_information.number_frame),num2str(header_information.number_marker),'mm',...
    num2str(header_information.rate_data_orignal),...
    num2str(header_information.frame_start_data_orignal),...
    num2str(header_information.number_frame_orignal)};
line_4 = [{'Frame#';'Time'};header_information.name_marker];
line_5 = [char(9),header_information.name_axis];
marker_header = {line_1;line_2;line_3;line_4;line_5};
marker_header = cellfun(@(x) strjoin(x,'\t'),marker_header,'UniformOutput',false);
end