function marker_label_actual = get_marker_label_actual()
marker_label_actual = {...
    'Top.Head','L.Acromium','R.Acromium','Sternum','L.ASIS','R.ASIS',...
'V.Sacral','L.Thigh.Front','L.Knee.Lat','L.Knee.Med','L.Shank.Front',...
'L.Ankle.Lat','L.Ankle.Med','L.Heel','L.Toe.Lat','L.Toe.Tip',...
'R.Thigh.Front','R.Knee.Lat','R.Knee.Med','R.Shank.Front','R.Ankle.Lat',...
'R.Ankle.Med','R.Heel','R.Toe.Lat','R.Toe.Tip'
};
end